/**
 * TZDB identifier → Arabic display name.
 * English always shows the raw TZDB ID (e.g. "Africa/Cairo").
 * Arabic shows the localised city/region name.
 */
export const TIMEZONE_NAMES_AR: Record<string, string> = {
  // Africa
  'Africa/Abidjan':        'أبيدجان',
  'Africa/Accra':          'أكرا',
  'Africa/Addis_Ababa':    'أديس أبابا',
  'Africa/Algiers':        'الجزائر',
  'Africa/Asmara':         'أسمرة',
  'Africa/Bamako':         'باماكو',
  'Africa/Bangui':         'بانغي',
  'Africa/Banjul':         'بانجول',
  'Africa/Bissau':         'بيساو',
  'Africa/Blantyre':       'بلانتير',
  'Africa/Brazzaville':    'برازافيل',
  'Africa/Bujumbura':      'بوجومبورا',
  'Africa/Cairo':          'القاهرة',
  'Africa/Casablanca':     'الدار البيضاء',
  'Africa/Ceuta':          'سبتة',
  'Africa/Conakry':        'كوناكري',
  'Africa/Dakar':          'داكار',
  'Africa/Dar_es_Salaam':  'دار السلام',
  'Africa/Djibouti':       'جيبوتي',
  'Africa/Douala':         'دوالا',
  'Africa/El_Aaiun':       'العيون',
  'Africa/Freetown':       'فريتاون',
  'Africa/Gaborone':       'غابورون',
  'Africa/Harare':         'هراري',
  'Africa/Johannesburg':   'جوهانسبرغ',
  'Africa/Juba':           'جوبا',
  'Africa/Kampala':        'كمبالا',
  'Africa/Khartoum':       'الخرطوم',
  'Africa/Kigali':         'كيغالي',
  'Africa/Kinshasa':       'كينشاسا',
  'Africa/Lagos':          'لاغوس',
  'Africa/Libreville':     'ليبرفيل',
  'Africa/Lome':           'لومي',
  'Africa/Luanda':         'لواندا',
  'Africa/Lubumbashi':     'لوبومباشي',
  'Africa/Lusaka':         'لوساكا',
  'Africa/Malabo':         'مالابو',
  'Africa/Maputo':         'مابوتو',
  'Africa/Maseru':         'ماسيرو',
  'Africa/Mbabane':        'مباباني',
  'Africa/Mogadishu':      'مقديشو',
  'Africa/Monrovia':       'مونروفيا',
  'Africa/Nairobi':        'نيروبي',
  'Africa/Ndjamena':       'نجامينا',
  'Africa/Niamey':         'نيامي',
  'Africa/Nouakchott':     'نواكشوط',
  'Africa/Ouagadougou':    'واغادوغو',
  'Africa/Porto-Novo':     'بورتو نوفو',
  'Africa/Sao_Tome':       'ساو تومي',
  'Africa/Tripoli':        'طرابلس',
  'Africa/Tunis':          'تونس',
  'Africa/Windhoek':       'ويندهوك',

  // America
  'America/Adak':                       'أداك',
  'America/Anchorage':                  'أنكوريدج',
  'America/Anguilla':                   'أنغيلا',
  'America/Antigua':                    'أنتيغوا',
  'America/Araguaina':                  'أراغوايينا',
  'America/Argentina/Buenos_Aires':     'بوينس آيرس',
  'America/Argentina/Catamarca':        'كاتاماركا',
  'America/Argentina/Cordoba':          'قرطبة (الأرجنتين)',
  'America/Argentina/Jujuy':            'خوخوي',
  'America/Argentina/La_Rioja':         'لا ريوخا',
  'America/Argentina/Mendoza':          'ميندوزا',
  'America/Argentina/Rio_Gallegos':     'ريو غاييغوس',
  'America/Argentina/Salta':            'سالتا',
  'America/Argentina/San_Juan':         'سان خوان',
  'America/Argentina/San_Luis':         'سان لويس',
  'America/Argentina/Tucuman':          'توكومان',
  'America/Argentina/Ushuaia':          'أوشوايا',
  'America/Aruba':                      'أروبا',
  'America/Asuncion':                   'أسونسيون',
  'America/Atikokan':                   'أتيكوكان',
  'America/Bahia':                      'باهيا',
  'America/Bahia_Banderas':             'باهيا بانديراس',
  'America/Barbados':                   'بربادوس',
  'America/Belem':                      'بيليم',
  'America/Belize':                     'بليز',
  'America/Blanc-Sablon':               'بلان سابلون',
  'America/Boa_Vista':                  'بوا فيستا',
  'America/Bogota':                     'بوغوتا',
  'America/Boise':                      'بويزي',
  'America/Cambridge_Bay':              'كامبريدج باي',
  'America/Campo_Grande':               'كامبو غراندي',
  'America/Cancun':                     'كانكون',
  'America/Caracas':                    'كاراكاس',
  'America/Cayenne':                    'كايين',
  'America/Cayman':                     'كايمان',
  'America/Chicago':                    'شيكاغو',
  'America/Chihuahua':                  'تشيواوا',
  'America/Costa_Rica':                 'كوستاريكا',
  'America/Creston':                    'كريستون',
  'America/Cuiaba':                     'كويابا',
  'America/Curacao':                    'كوراساو',
  'America/Danmarkshavn':               'دانماركسهافن',
  'America/Dawson':                     'داوسون',
  'America/Dawson_Creek':               'داوسون كريك',
  'America/Denver':                     'دنفر',
  'America/Detroit':                    'ديترويت',
  'America/Dominica':                   'دومينيكا',
  'America/Edmonton':                   'إدمونتون',
  'America/Eirunepe':                   'إيرونيبي',
  'America/El_Salvador':                'السلفادور',
  'America/Fortaleza':                  'فورتاليزا',
  'America/Glace_Bay':                  'غليس باي',
  'America/Godthab':                    'غودهاب',
  'America/Goose_Bay':                  'غوس باي',
  'America/Grand_Turk':                 'غراند تورك',
  'America/Grenada':                    'غرينادا',
  'America/Guadeloupe':                 'غوادلوب',
  'America/Guatemala':                  'غواتيمالا',
  'America/Guayaquil':                  'غواياكيل',
  'America/Guyana':                     'غيانا',
  'America/Halifax':                    'هاليفاكس',
  'America/Havana':                     'هافانا',
  'America/Hermosillo':                 'هيرموسيلو',
  'America/Indiana/Indianapolis':       'إنديانابوليس',
  'America/Indiana/Knox':               'نوكس',
  'America/Indiana/Marengo':            'مارينغو',
  'America/Indiana/Petersburg':         'بيترسبرغ',
  'America/Indiana/Tell_City':          'تيل سيتي',
  'America/Indiana/Vevay':              'فيفاي',
  'America/Indiana/Vincennes':          'فينسينس',
  'America/Indiana/Winamac':            'ويناماك',
  'America/Inuvik':                     'إينوفيك',
  'America/Iqaluit':                    'إيقالويت',
  'America/Jamaica':                    'جامايكا',
  'America/Juneau':                     'جونو',
  'America/Kentucky/Louisville':        'لويزفيل',
  'America/Kentucky/Monticello':        'مونتيسيلو',
  'America/Kralendijk':                 'كراليندايك',
  'America/La_Paz':                     'لاباز',
  'America/Lima':                       'ليما',
  'America/Los_Angeles':                'لوس أنجلوس',
  'America/Lower_Princes':              'لوير برينسز كوارتر',
  'America/Maceio':                     'ماسيو',
  'America/Managua':                    'ماناغوا',
  'America/Manaus':                     'ماناوس',
  'America/Marigot':                    'ماريغو',
  'America/Martinique':                 'مارتينيك',
  'America/Matamoros':                  'ماتاموروس',
  'America/Mazatlan':                   'مازاتلان',
  'America/Menominee':                  'مينوميني',
  'America/Merida':                     'ميريدا',
  'America/Metlakatla':                 'ميتلاكاتلا',
  'America/Mexico_City':                'مكسيكو سيتي',
  'America/Miquelon':                   'ميكلون',
  'America/Moncton':                    'مونكتون',
  'America/Monterrey':                  'مونتيري',
  'America/Montevideo':                 'مونتيفيديو',
  'America/Montserrat':                 'مونتسيرات',
  'America/Nassau':                     'ناسو',
  'America/New_York':                   'نيويورك',
  'America/Nipigon':                    'نيبيغون',
  'America/Nome':                       'نوم',
  'America/Noronha':                    'نورونها',
  'America/North_Dakota/Beulah':        'بيولا',
  'America/North_Dakota/Center':        'سنتر',
  'America/North_Dakota/New_Salem':     'نيو سالم',
  'America/Ojinaga':                    'أوخيناغا',
  'America/Panama':                     'بنما',
  'America/Pangnirtung':                'بانغنيرتونغ',
  'America/Paramaribo':                 'باراماريبو',
  'America/Phoenix':                    'فينيكس',
  'America/Port-au-Prince':             'بورت أوبرانس',
  'America/Port_of_Spain':              'بورت أوف سبين',
  'America/Porto_Velho':                'بورتو فيلهو',
  'America/Puerto_Rico':                'بورتوريكو',
  'America/Punta_Arenas':              'بونتا أريناس',
  'America/Rainy_River':                'ريني ريفر',
  'America/Rankin_Inlet':               'رانكن إنليت',
  'America/Recife':                     'ريسيفي',
  'America/Regina':                     'ريجينا',
  'America/Resolute':                   'ريزولوت',
  'America/Rio_Branco':                 'ريو برانكو',
  'America/Santa_Isabel':               'سانتا إيزابيل',
  'America/Santarem':                   'سانتاريم',
  'America/Santiago':                   'سانتياغو',
  'America/Santo_Domingo':              'سانتو دومينغو',
  'America/Sao_Paulo':                  'ساو باولو',
  'America/Scoresbysund':               'سكوريسبيسند',
  'America/Sitka':                      'سيتكا',
  'America/St_Barthelemy':              'سان بارتيليمي',
  'America/St_Johns':                   'سانت جونز',
  'America/St_Kitts':                   'سانت كيتس',
  'America/St_Lucia':                   'سانت لوسيا',
  'America/St_Thomas':                  'سانت توماس',
  'America/St_Vincent':                 'سانت فنسنت',
  'America/Swift_Current':              'سويفت كارنت',
  'America/Tegucigalpa':                'تيغوسيغالبا',
  'America/Thule':                      'ثول',
  'America/Thunder_Bay':                'ثاندر باي',
  'America/Tijuana':                    'تيخوانا',
  'America/Toronto':                    'تورنتو',
  'America/Tortola':                    'تورتولا',
  'America/Vancouver':                  'فانكوفر',
  'America/Whitehorse':                 'وايتهورس',
  'America/Winnipeg':                   'وينيبيغ',
  'America/Yakutat':                    'ياكوتات',
  'America/Yellowknife':                'يلونايف',

  // Antarctica
  'Antarctica/Casey':          'كيسي',
  'Antarctica/Davis':          'ديفيس',
  'Antarctica/DumontDUrville': 'دومون دورفيل',
  'Antarctica/Macquarie':      'ماكواري',
  'Antarctica/Mawson':         'موسون',
  'Antarctica/McMurdo':        'ماكموردو',
  'Antarctica/Palmer':         'بالمر',
  'Antarctica/Rothera':        'روثيرا',
  'Antarctica/Syowa':          'سيووا',
  'Antarctica/Troll':          'ترول',
  'Antarctica/Vostok':         'فوستوك',

  // Arctic
  'Arctic/Longyearbyen': 'لونغيربين',

  // Asia
  'Asia/Aden':          'عدن',
  'Asia/Almaty':        'ألماتي',
  'Asia/Amman':         'عمّان',
  'Asia/Anadyr':        'أناديير',
  'Asia/Aqtau':         'أكتاو',
  'Asia/Aqtobe':        'أكتوبي',
  'Asia/Ashgabat':      'عشق آباد',
  'Asia/Atyrau':        'أتيراو',
  'Asia/Baghdad':       'بغداد',
  'Asia/Bahrain':       'البحرين',
  'Asia/Baku':          'باكو',
  'Asia/Bangkok':       'بانكوك',
  'Asia/Barnaul':       'بارناول',
  'Asia/Beirut':        'بيروت',
  'Asia/Bishkek':       'بيشكيك',
  'Asia/Brunei':        'بروناي',
  'Asia/Chita':         'تشيتا',
  'Asia/Choibalsan':    'تشويبالسان',
  'Asia/Colombo':       'كولومبو',
  'Asia/Damascus':      'دمشق',
  'Asia/Dhaka':         'دكا',
  'Asia/Dili':          'ديلي',
  'Asia/Dubai':         'دبي',
  'Asia/Dushanbe':      'دوشانبي',
  'Asia/Famagusta':     'فاماغوستا',
  'Asia/Gaza':          'غزة',
  'Asia/Hebron':        'الخليل',
  'Asia/Ho_Chi_Minh':   'هو تشي منه',
  'Asia/Hong_Kong':     'هونغ كونغ',
  'Asia/Hovd':          'هوفد',
  'Asia/Irkutsk':       'إيركوتسك',
  'Asia/Jakarta':       'جاكرتا',
  'Asia/Jayapura':      'جايابورا',
  'Asia/Jerusalem':     'القدس',
  'Asia/Kabul':         'كابول',
  'Asia/Kamchatka':     'كامتشاتكا',
  'Asia/Karachi':       'كراتشي',
  'Asia/Kathmandu':     'كاتماندو',
  'Asia/Khandyga':      'خانديغا',
  'Asia/Kolkata':       'كولكاتا',
  'Asia/Krasnoyarsk':   'كراسنويارسك',
  'Asia/Kuala_Lumpur':  'كوالالمبور',
  'Asia/Kuching':       'كوتشينغ',
  'Asia/Kuwait':        'الكويت',
  'Asia/Macau':         'ماكاو',
  'Asia/Magadan':       'ماغادان',
  'Asia/Makassar':      'ماكاسار',
  'Asia/Manila':        'مانيلا',
  'Asia/Muscat':        'مسقط',
  'Asia/Nicosia':       'نيقوسيا',
  'Asia/Novokuznetsk':  'نوفوكوزنيتسك',
  'Asia/Novosibirsk':   'نوفوسيبيرسك',
  'Asia/Omsk':          'أومسك',
  'Asia/Oral':          'أورال',
  'Asia/Phnom_Penh':    'بنوم بنه',
  'Asia/Pontianak':     'بونتيانك',
  'Asia/Pyongyang':     'بيونغ يانغ',
  'Asia/Qatar':         'قطر',
  'Asia/Qostanay':      'قوستاناي',
  'Asia/Qyzylorda':     'قيزيل أوردا',
  'Asia/Riyadh':        'الرياض',
  'Asia/Sakhalin':      'سخالين',
  'Asia/Samarkand':     'سمرقند',
  'Asia/Seoul':         'سيول',
  'Asia/Shanghai':      'شنغهاي',
  'Asia/Singapore':     'سنغافورة',
  'Asia/Srednekolymsk': 'سريدنيكوليمسك',
  'Asia/Taipei':        'تايبيه',
  'Asia/Tashkent':      'طشقند',
  'Asia/Tbilisi':       'تبليسي',
  'Asia/Tehran':        'طهران',
  'Asia/Thimphu':       'تيمفو',
  'Asia/Tokyo':         'طوكيو',
  'Asia/Tomsk':         'تومسك',
  'Asia/Ulaanbaatar':   'أولان باتور',
  'Asia/Urumqi':        'أورومتشي',
  'Asia/Ust-Nera':      'أوست نيرا',
  'Asia/Vientiane':     'فيينتيان',
  'Asia/Vladivostok':   'فلاديفوستوك',
  'Asia/Yakutsk':       'ياقوتسك',
  'Asia/Yangon':        'يانغون',
  'Asia/Yekaterinburg': 'يكاترينبرغ',
  'Asia/Yerevan':       'يريفان',

  // Atlantic
  'Atlantic/Azores':         'جزر الأزور',
  'Atlantic/Bermuda':        'برمودا',
  'Atlantic/Canary':         'جزر الكناري',
  'Atlantic/Cape_Verde':     'الرأس الأخضر',
  'Atlantic/Faroe':          'جزر فارو',
  'Atlantic/Madeira':        'ماديرا',
  'Atlantic/Reykjavik':      'ريكيافيك',
  'Atlantic/South_Georgia':  'جورجيا الجنوبية',
  'Atlantic/St_Helena':      'سانت هيلينا',
  'Atlantic/Stanley':        'ستانلي',

  // Australia
  'Australia/Adelaide':    'أديلايد',
  'Australia/Brisbane':    'بريسبان',
  'Australia/Broken_Hill': 'بروكن هيل',
  'Australia/Darwin':      'داروين',
  'Australia/Eucla':       'يوكلا',
  'Australia/Hobart':      'هوبارت',
  'Australia/Lindeman':    'ليندمان',
  'Australia/Lord_Howe':   'لورد هاو',
  'Australia/Melbourne':   'ملبورن',
  'Australia/Perth':       'بيرث',
  'Australia/Sydney':      'سيدني',

  // Europe
  'Europe/Amsterdam':   'أمستردام',
  'Europe/Andorra':     'أندورا',
  'Europe/Astrakhan':   'أستراخان',
  'Europe/Athens':      'أثينا',
  'Europe/Belgrade':    'بلغراد',
  'Europe/Berlin':      'برلين',
  'Europe/Bratislava':  'براتيسلافا',
  'Europe/Brussels':    'بروكسل',
  'Europe/Bucharest':   'بوخارست',
  'Europe/Budapest':    'بودابست',
  'Europe/Busingen':    'بوسينغن',
  'Europe/Chisinau':    'كيشيناو',
  'Europe/Copenhagen':  'كوبنهاغن',
  'Europe/Dublin':      'دبلن',
  'Europe/Gibraltar':   'جبل طارق',
  'Europe/Guernsey':    'غيرنسي',
  'Europe/Helsinki':    'هلسنكي',
  'Europe/Isle_of_Man': 'جزيرة مان',
  'Europe/Istanbul':    'إسطنبول',
  'Europe/Jersey':      'جيرسي',
  'Europe/Kaliningrad': 'كالينينغراد',
  'Europe/Kiev':        'كييف',
  'Europe/Kirov':       'كيروف',
  'Europe/Lisbon':      'لشبونة',
  'Europe/Ljubljana':   'ليوبليانا',
  'Europe/London':      'لندن',
  'Europe/Luxembourg':  'لوكسمبورغ',
  'Europe/Madrid':      'مدريد',
  'Europe/Malta':       'مالطا',
  'Europe/Mariehamn':   'ماريهامن',
  'Europe/Minsk':       'مينسك',
  'Europe/Monaco':      'موناكو',
  'Europe/Moscow':      'موسكو',
  'Europe/Nicosia':     'نيقوسيا',
  'Europe/Oslo':        'أوسلو',
  'Europe/Paris':       'باريس',
  'Europe/Podgorica':   'بودغوريتسا',
  'Europe/Prague':      'براغ',
  'Europe/Riga':        'ريغا',
  'Europe/Rome':        'روما',
  'Europe/Samara':      'سامارا',
  'Europe/San_Marino':  'سان مارينو',
  'Europe/Sarajevo':    'سراييفو',
  'Europe/Saratov':     'ساراتوف',
  'Europe/Simferopol':  'سيمفيروبول',
  'Europe/Skopje':      'سكوبية',
  'Europe/Sofia':       'صوفيا',
  'Europe/Stockholm':   'ستوكهولم',
  'Europe/Tallinn':     'تالين',
  'Europe/Tirane':      'تيرانا',
  'Europe/Ulyanovsk':   'أوليانوفسك',
  'Europe/Uzhgorod':    'أوجغورود',
  'Europe/Vaduz':       'فادوز',
  'Europe/Vatican':     'الفاتيكان',
  'Europe/Vienna':      'فيينا',
  'Europe/Vilnius':     'فيلنيوس',
  'Europe/Volgograd':   'فولغوغراد',
  'Europe/Warsaw':      'وارسو',
  'Europe/Zagreb':      'زغرب',
  'Europe/Zaporozhye':  'زابوروجيه',
  'Europe/Zurich':      'زيورخ',

  // Indian
  'Indian/Antananarivo': 'أنتاناناريفو',
  'Indian/Chagos':       'جزر تشاغوس',
  'Indian/Christmas':    'جزيرة الكريسماس',
  'Indian/Cocos':        'جزر كوكوس',
  'Indian/Comoro':       'جزر القمر',
  'Indian/Kerguelen':    'كيرغيلن',
  'Indian/Mahe':         'ماهي',
  'Indian/Maldives':     'المالديف',
  'Indian/Mauritius':    'موريشيوس',
  'Indian/Mayotte':      'مايوت',
  'Indian/Reunion':      'ريونيون',

  // Pacific
  'Pacific/Apia':         'أبيا',
  'Pacific/Auckland':     'أوكلاند',
  'Pacific/Bougainville': 'بوغانفيل',
  'Pacific/Chatham':      'تشاتام',
  'Pacific/Chuuk':        'تشوك',
  'Pacific/Easter':       'جزيرة الفصح',
  'Pacific/Efate':        'إيفاتي',
  'Pacific/Enderbury':    'إندربري',
  'Pacific/Fakaofo':      'فاكاوفو',
  'Pacific/Fiji':         'فيجي',
  'Pacific/Funafuti':     'فونافوتي',
  'Pacific/Galapagos':    'غالاباغوس',
  'Pacific/Gambier':      'غامبييه',
  'Pacific/Guadalcanal':  'غوادالكانال',
  'Pacific/Guam':         'غوام',
  'Pacific/Honolulu':     'هونولولو',
  'Pacific/Kiritimati':   'كيريتيماتي',
  'Pacific/Kosrae':       'كوسراي',
  'Pacific/Kwajalein':    'كواجالين',
  'Pacific/Majuro':       'ماجورو',
  'Pacific/Marquesas':    'ماركيساس',
  'Pacific/Midway':       'ميدواي',
  'Pacific/Nauru':        'ناورو',
  'Pacific/Niue':         'نيوي',
  'Pacific/Norfolk':      'نورفولك',
  'Pacific/Noumea':       'نوميا',
  'Pacific/Pago_Pago':    'باغو باغو',
  'Pacific/Palau':        'بالاو',
  'Pacific/Pitcairn':     'بيتكيرن',
  'Pacific/Pohnpei':      'بونبي',
  'Pacific/Port_Moresby': 'بورت مورسبي',
  'Pacific/Rarotonga':    'راروتونغا',
  'Pacific/Saipan':       'سايبان',
  'Pacific/Tahiti':       'تاهيتي',
  'Pacific/Tarawa':       'تاراوا',
  'Pacific/Tongatapu':    'تونغاتابو',
  'Pacific/Wake':         'جزيرة ويك',
  'Pacific/Wallis':       'واليس',

  // UTC
  'UTC': 'التوقيت العالمي (UTC)'
};
